language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
    - node_modules
env:
  global:
  - CXX="g++-4.8"
notifications:
  email: false
